language: node_js
node_js:
  - "stable"
notifications:
  email: false
services:
  - postgresql
cache:
  directories:
    - node_modules
before_script:
  - npm install
  - psql -c "CREATE DATABASE quickcredittest;" -U postgres
env:
  - SECRET=gwe4rt46556456545gt3456
script: 
  - npm run test
after_success:
  - npm run coverage
  - npm run report-coverage
  - npm run coveralls